spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.17.7.22/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
server:
  servlet:
    context-path: /sell
